### PR TITLE
testing mergeable with atlantis/apply

### PR DESCRIPTION
**Pull request by zepeng811**

### CODE REVIEW

**Comment by zepeng811** [comment]
Ran Plan for project: `atlantis-dev` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_branch.branch will be created
+ resource "github_branch" "branch" {
      + branch        = "tf-branch-1"
      + etag          = (known after apply)
      + id            = (known after apply)
      + ref           = (known after apply)
      + repository    = "atlantis-dev"
      + sha           = (known after apply)
      + source_branch = "master"
      + source_sha    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p atlantis-dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ea618f048c2a:4141/lock?id=zepeng811%252Fatlantis-dev%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p atlantis-dev`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by zhpeng811 — APPROVED** [review]

**Comment by zepeng811** [comment]
atlantis apply

**Comment by zepeng811** [comment]
Ran Apply for project: `atlantis-dev` dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/zepeng811/atlantis-dev/3/default/atlantis-dev-default.tfplan\"" in "/home/atlantis/.atlantis/repos/zepeng811/atlantis-dev/3/default": exit status 1
github_branch.branch: Creating...
╷
│ Error: Error querying GitHub branch reference /atlantis-dev (refs/heads/master): GET https://api.github.com/repos//atlantis-dev/git/ref/heads/master: 404 Not Found []
│ 
│   with github_branch.branch,
│   on main.tf line 13, in resource "github_branch" "branch":
│   13: resource "github_branch" "branch" {
│ 
╵

```

**Comment by zepeng811** [comment]
atlantis plan

**Comment by zepeng811** [comment]
Ran Plan for project: `atlantis-dev` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_branch.branch will be created
+ resource "github_branch" "branch" {
      + branch        = "tf-branch-1"
      + etag          = (known after apply)
      + id            = (known after apply)
      + ref           = (known after apply)
      + repository    = "atlantis-dev"
      + sha           = (known after apply)
      + source_branch = "master"
      + source_sha    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p atlantis-dev`
* :put_litter_in_its_place: To **delete** this plan click [here](http://e330d6c7f633:4141/lock?id=zepeng811%252Fatlantis-dev%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p atlantis-dev`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by zepeng811** [comment]
atlantis apply

**Comment by zepeng811** [comment]
Ran Apply for project: `atlantis-dev` dir: `.` workspace: `default`

```diff
github_branch.branch: Creating...
github_branch.branch: Creation complete after 2s [id=atlantis-dev:tf-branch-1]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by zepeng811** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by zepeng811** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
